CoronaPredictionsAspNetCore/Models/Predictions.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CoronaPredictionsAspNetCore.Models
{
    public class Predictions
    {
        [Key]
        [Required]
        public int PredictionID { get; set; }
        [Required]
        [DisplayName("Day Of Prediction")]
        public DayOfWeek DayOfPrediction { get; set; }
        [Required]
        [DisplayName("Date Of Prediction")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public DateTime DateOfPrediction { get; set; }
        [Required]
        [MaxLength(50)]
        [DisplayName("Player Name")]
        public string PlayerName { get; set; }
        [Required]
        [DisplayName("Cases Of Prediction")]
        public int CasesOfPrediction { get; set; }
        [NotMapped]
        public SelectList PlayersList { get; set; }
    }
    public class User
    {
        public string Key { get; set; }
        public string Display { get; set; }
    }
}

CoronaPredictionsAspNetCore/Controllers/PredictionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoronaPredictionsAspNetCore.Models;
using CoronaPredictionsAspNetCore.DataAccessLayer;
using ReflectionIT.Mvc.Paging;

namespace CoronaPredictionsAspNetCore.Controllers
{
 
    public class PredictionsController : Controller
    {
        private readonly PredictCoronaCasesDBContext _context;
     

        public PredictionsController(PredictCoronaCasesDBContext context)
        {
            _context = context; 
        }
       
        // GET: Predictions
        public async Task<IActionResult> Index( DateTime searchDate, int page)
        {
            var pageIndex = (page == 0) ? 1 : page;              
            var pageQuery = _context.Prediction.AsNoTracking().OrderBy(x => x.DateOfPrediction);
            if (searchDate != DateTime.MinValue) {
                pageQuery = pageQuery.Where(c => c.DateOfPrediction == searchDate).OrderBy(x => x.DateOfPrediction);
            }
            var modelIndex = await PagingList.CreateAsync(pageQuery, _context.Players.Count(), pageIndex);
            return View(modelIndex);
        }
       
        // GET: Predictions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var predictions = await _context.Prediction
                .FirstOrDefaultAsync(m => m.PredictionID == id);
            if (predictions == null)
            {
                return NotFound();
            }

            return View(predictions);
        }
        public IEnumerable<Player> displayData { get; set; }
        public async Task OnGet() {
            displayData = await _context.Players.ToListAsync();
        }
        // GET: Predictions/Create
        public IActionResult Create()
        {
            var list = new List<User>();
            var playerNames =  _context.Players.OrderBy(y=>y.Name).Select(x=>x.Name).ToList();
            foreach (var item in playerNames)
            {
                list.Add(new User
                {
                    Key = item,
                    Display = item
                });
            }
            var model = new Predictions();
            model.CasesOfPrediction = 0;
            model.DateOfPrediction =  DateTime.Parse(DateTime.Now.ToString("dddd, dd MMMM yyyy"));
            model.DayOfPrediction = DateTime.Today.DayOfWeek;
            model.PlayersList = new SelectList(list, "Key", "Display");
            return View(model);
        }

        // POST: Predictions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PredictionID,DayOfPrediction,DateOfPrediction,PlayerName,CasesOfPrediction")] Predictions predictions)
        {
            var DateOfRealCase = predictions.DateOfPrediction.DayOfWeek;
            var DayOfRealCase = predictions.DayOfPrediction;
            if (DateOfRealCase == DayOfRealCase)
            {
                if (ModelState.IsValid)
                {
                    _context.Add(predictions);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                ModelState.AddModelError("DateOfPrediction", "Date of Prediction does not match with its date of week");
            }
            var list = new List<User>();
            var playerNames = _context.Players.OrderBy(y => y.Name).Select(x => x.Name).ToList();
            foreach (var item in playerNames)
            {
                list.Add(new User
                {
                    Key = item,
                    Display = item
                });
            }
            predictions.PlayersList = new SelectList(list, "Key", "Display");
            return View(predictions);
        }

        // GET: Predictions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var predictions = await _context.Prediction.FindAsync(id);
            if (predictions == null)
            {
                return NotFound();
            }
            var list = new List<User>();
            var playerNames = _context.Players.OrderBy(y => y.Name).Select(x => x.Name).ToList();
            foreach (var item in playerNames)
            {
                list.Add(new User
                {
                    Key = item,
                    Display = item
                });
            }
            predictions.PlayersList = new SelectList(list, "Key", "Display");
            return View(predictions);
        }

        // POST: Predictions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PredictionID,DayOfPrediction,DateOfPrediction,PlayerName,CasesOfPrediction")] Predictions predictions)
        {
            if (id != predictions.PredictionID)
            {
                return NotFound();
            }
            var DateOfRealCase = predictions.DateOfPrediction.DayOfWeek;
            var DayOfRealCase = predictions.DayOfPrediction;
            if (DateOfRealCase == DayOfRealCase)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(predictions);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!PredictionsExists(predictions.PredictionID))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                ModelState.AddModelError("DateOfPrediction", "Date of Prediction does not match with its date of week");
            }
            var list = new List<User>();
            var playerNames = _context.Players.OrderBy(y => y.Name).Select(x => x.Name).ToList();
            foreach (var item in playerNames)
            {
                list.Add(new User
                {
                    Key = item,
                    Display = item
                });
            }
            predictions.PlayersList = new SelectList(list, "Key", "Display");
            return View(predictions);
        }

        // GET: Predictions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var predictions = await _context.Prediction
                .FirstOrDefaultAsync(m => m.PredictionID == id);
            if (predictions == null)
            {
                return NotFound();
            }

            return View(predictions);
        }

        // POST: Predictions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var predictions = await _context.Prediction.FindAsync(id);
            _context.Prediction.Remove(predictions);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PredictionsExists(int id)
        {
            return _context.Prediction.Any(e => e.PredictionID == id);
        }
    }
}

CoronaPredictionsAspNetCore/Views/Predictions/Create.cshtml
@model CoronaPredictionsAspNetCore.Models.Predictions

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Predictions</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DayOfPrediction" class="control-label"></label>
                <select asp-for="DayOfPrediction" class="form-control" >
                    <option value="" selected disabled>Please select day</option>
                    <option>Sunday</option>
                    <option>Monday</option>
                    <option>Tuesday</option>
                    <option>Wednesday</option>
                    <option>Thursday</option>
                    <option>Friday</option>
                    <option>Saturday</option>
                </select>
                <span asp-validation-for="DayOfPrediction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfPrediction" class="control-label"></label>
                <input asp-for="DateOfPrediction" class="form-control" />
                <span asp-validation-for="DateOfPrediction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerName" class="control-label"></label>
                <br>
                <select id="Select1" asp-for="PlayerName" asp-items="@(new SelectList(Model.PlayersList.Items,"Key","Display"))">
                    <option value="" selected disabled>Select Player</option>
                </select>
            </div>
            @*<div class="form-group">
                    <label asp-for="PlayerName" class="control-label"></label>
                    <input asp-for="PlayerName" class="form-control" />
                    <span asp-validation-for="PlayerName" class="text-danger"></span>
                </div>*@


            <div class="form-group">
                <label asp-for="CasesOfPrediction" class="control-label"></label>
                <input asp-for="CasesOfPrediction" class="form-control" />
                <span asp-validation-for="CasesOfPrediction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input id="submitBtn" type="submit" value="Create" class="btn btn-primary" onclick="return selectedPlayer();"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script type="text/javascript">
    function selectedPlayer() {
        if ($("#Select1 :selected").text()=="Select Player") {
            alert("Please select Player Name from list");
        }
              
   return true;
    }

</script>

CoronaPredictionsAspNetCore/Views/Predictions/Delete.cshtml
@model CoronaPredictionsAspNetCore.Models.Predictions

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
<div>
    <h4>Predictions</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DayOfPrediction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DayOfPrediction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfPrediction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfPrediction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CasesOfPrediction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CasesOfPrediction)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="row">           
            <div class="mx-2" style="width: 20px;">
                <i class="fas fa-trash-alt fa-2x"></i>
            </div>
            <div class="mx-2" style="width: 70px;">
                <input type="hidden" asp-for="PredictionID" />
                <input type="submit" value="Delete" class="btn btn-outline-danger" />
            </div>
            <div class="mx-2" style="width: 150px;">
                <a asp-action="Index" class="btn btn-outline-primary" type="reset"> Back to List</a>
            </div>
        </div>
    </form>
</div>

CoronaPredictionsAspNetCore/Views/Predictions/Details.cshtml
@model CoronaPredictionsAspNetCore.Models.Predictions

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
<div>
    <h4>Predictions</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DayOfPrediction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DayOfPrediction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfPrediction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfPrediction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CasesOfPrediction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CasesOfPrediction)
        </dd>
    </dl>
</div>
<div>
    <div class="row">
        <div class="mx-2" style="width: 75px; ">
            <a asp-action="Edit" asp-route-id="@Model.PredictionID"><i class="fas fa-edit fa-2x"></i>Edit</a>
        </div>
            <div class="mx-2" style="width: 150px;">
                <a asp-action="Index" class="btn btn-outline-primary" type="reset"> Back to List</a>
            </div>
    </div>
</div>

CoronaPredictionsAspNetCore/Views/Predictions/Edit.cshtml
@model CoronaPredictionsAspNetCore.Models.Predictions

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>


@section Scripts{
    <script src="jquery-ui.min.js"></script>
    <script >
        $(document).ready(function () {
            $("#DateOfPrediction").datepicker();
        });

    </script>
}

<h4>Predictions</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PredictionID" />
            <div class="form-group">
                <label asp-for="DayOfPrediction" class="control-label"></label>
                <select asp-for="DayOfPrediction" class="form-control">
                    <option>Please select one</option>
                    <option>Sunday</option>
                    <option>Monday</option>
                    <option>Tuesday</option>
                    <option>Wednesday</option>
                    <option>Thursday</option>
                    <option>Friday</option>
                    <option>Saturday</option>
                </select>
                <span asp-validation-for="DayOfPrediction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfPrediction" class="control-label"></label>
                <input asp-for="DateOfPrediction" class="form-control" />
                <span asp-validation-for="DateOfPrediction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerName" class="control-label"></label>
                <br>
                <select id="Select2" asp-for="PlayerName" asp-items="@(new SelectList(Model.PlayersList.Items,"Key","Display"))">
                    <option value="" selected disabled>Select Player</option>
                </select>
            </div>
            @*<div class="form-group">
                <label asp-for="PlayerName" class="control-label"></label>
                <input asp-for="PlayerName" class="form-control" />
                <span asp-validation-for="PlayerName" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="CasesOfPrediction" class="control-label"></label>
                <input asp-for="CasesOfPrediction" class="form-control" />
                <span asp-validation-for="CasesOfPrediction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-success" />
                <a asp-action="Index" class="btn btn-outline-primary" type="reset">Back to List</a>
            </div>
        </form>
    </div>
</div>

CoronaPredictionsAspNetCore/Views/Predictions/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<CoronaPredictionsAspNetCore.Models.Predictions>
@using ReflectionIT.Mvc.Paging
@addTagHelper *,ReflectionIT.Mvc.Paging
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<nav aria-label="Pagination Navigation">
    @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
</nav>

<p>
    <a asp-action="Create">Create New</a>
</p>
@using (Html.BeginForm("Index", "Predictions", FormMethod.Post))
{
    <p></p>
    <div>
        Search by Date Of Prediction: @Html.TextBox("searchDate")
        <input id="Submit1" type="submit" value="Filter" />
    </div>
}
<p></p>
<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DayOfPrediction)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfPrediction)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CasesOfPrediction)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DayOfPrediction)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfPrediction)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CasesOfPrediction)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.PredictionID"><i class="fas fa-edit"></i> Edit </a>  
                    <a asp-action="Details" asp-route-id="@item.PredictionID"><i class="fas fa-info"></i> Details </a> 
                    <a asp-action="Delete" asp-route-id="@item.PredictionID"><i class="fas fa-trash-alt"></i> Delete </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<nav aria-label="Pagination Navigation">
    <vc:pager paging-list="@Model" />
</nav>