CoronaPredictionsAspNetCore/Controllers/PlayerOfDayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoronaPredictionsAspNetCore.DataAccessLayer;
using CoronaPredictionsAspNetCore.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoronaPredictionsAspNetCore.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class PlayerOfDayController : Controller
    {
     
        private readonly IPredictionsRepo _repository;
        public PlayerOfDayController(IPredictionsRepo repository)
        {
            _repository = repository;
        }
        // GET: PlayerOfDay
        [HttpGet]
        public ActionResult<IEnumerable<PlayerOfDay>> PlayersOfTheDay()
        {         
                var bestPlayersByDate = _repository.BestPlayersByDate();        
            return View(bestPlayersByDate);
        }
    }
}

CoronaPredictionsAspNetCore/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoronaPredictionsAspNetCore.Models;

namespace CoronaPredictionsAspNetCore.Controllers
{
    public class PlayersController : Controller
    {
        private readonly PredictCoronaCasesDBContext _context;

        public PlayersController(PredictCoronaCasesDBContext context)
        {
            _context = context;
        }

        // GET: Players
        public async Task<IActionResult> Index()
        {
            return View(await _context.Players.OrderBy(y => y.Name).ToListAsync());
        }

        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .FirstOrDefaultAsync(m => m.PlayerID == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlayerID,Name,Nickname,WorkDescription")] Player player)
        {
            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players.FindAsync(id);
            if (player == null)
            {
                return NotFound();
            }
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PlayerID,Name,Nickname,WorkDescription")] Player player)
        {
            if (id != player.PlayerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.PlayerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .FirstOrDefaultAsync(m => m.PlayerID == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var player = await _context.Players.FindAsync(id);
            _context.Players.Remove(player);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerExists(int id)
        {
            return _context.Players.Any(e => e.PlayerID == id);
        }
    }
}

CoronaPredictionsAspNetCore/Controllers/RealCasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoronaPredictionsAspNetCore.Models;

namespace CoronaPredictionsAspNetCore.Controllers
{
    public class RealCasesController : Controller
    {
        private readonly PredictCoronaCasesDBContext _context;

        public RealCasesController(PredictCoronaCasesDBContext context)
        {
            _context = context;
        }

        // GET: RealCases
        public async Task<IActionResult> Index()
        {
            return View(await _context.RealCasesEachDay.OrderBy(x => x.DateOfRealCases).ToListAsync());
        }

        // GET: RealCases/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var realCases = await _context.RealCasesEachDay
                .FirstOrDefaultAsync(m => m.RealCaseID == id);
            if (realCases == null)
            {
                return NotFound();
            }

            return View(realCases);
        }

        // GET: RealCases/Create
        public IActionResult Create()
        {
            var list = new List<User>();
            var playerNames = _context.Players.Select(x => x.Name).ToList();
            foreach (var item in playerNames)
            {
                list.Add(new User
                {
                    Key = item,
                    Display = item
                });
            }
            var model = new RealCases();
            model.RealCasesNo = 0;
            model.DateOfRealCases = DateTime.Today;
            model.DayOfRealCases = DateTime.Today.DayOfWeek;
            return View(model);
        }

        // POST: RealCases/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RealCaseID,DayOfRealCases,DateOfRealCases,RealCasesNo")] RealCases realCases)
        {
            var DateOfRealCase = realCases.DateOfRealCases.DayOfWeek;
            var DayOfRealCase = realCases.DayOfRealCases;
            if (DateOfRealCase == DayOfRealCase)
            {
                if (ModelState.IsValid)
                {
                    _context.Add(realCases);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            else {
                ModelState.AddModelError("DateOfRealCases", "Date of Real Case does not match with its date of week");
            }
            
            return View(realCases);
        }

        // GET: RealCases/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var realCases = await _context.RealCasesEachDay.FindAsync(id);
            if (realCases == null)
            {
                return NotFound();
            }
            return View(realCases);
        }

        // POST: RealCases/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RealCaseID,DayOfRealCases,DateOfRealCases,RealCasesNo")] RealCases realCases)
        {
            if (id != realCases.RealCaseID)
            {
                return NotFound();
            }
            var DateOfRealCase = realCases.DateOfRealCases.DayOfWeek;
            var DayOfRealCase = realCases.DayOfRealCases;
            if (DateOfRealCase == DayOfRealCase)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(realCases);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!RealCasesExists(realCases.RealCaseID))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
            }
            else {
                ModelState.AddModelError("DateOfRealCases", "Date of Real Case does not match with its date of week");
            }
               
            return View(realCases);
        }

        // GET: RealCases/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var realCases = await _context.RealCasesEachDay
                .FirstOrDefaultAsync(m => m.RealCaseID == id);
            if (realCases == null)
            {
                return NotFound();
            }

            return View(realCases);
        }

        // POST: RealCases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var realCases = await _context.RealCasesEachDay.FindAsync(id);
            _context.RealCasesEachDay.Remove(realCases);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RealCasesExists(int id)
        {
            return _context.RealCasesEachDay.Any(e => e.RealCaseID == id);
        }
    }
}

CoronaPredictionsAspNetCore/Controllers/StandingsController.cs
using CoronaPredictionsAspNetCore.DataAccessLayer;
using CoronaPredictionsAspNetCore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoronaPredictionsAspNetCore.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class StandingsController :Controller
    {
        private readonly IPredictionsRepo _repository;
        public StandingsController(IPredictionsRepo repository)
        {
            _repository = repository;
        }
        // GET: Standings
        [HttpGet]
        public ActionResult<IEnumerable<Standings>> OverallStandings()
        {
            List<Standings> standings = new List<Standings>();
            List<Standings> standingsDynamically = new List<Standings>();
            standingsDynamically.AddRange(_repository.playersInStandings());
            var allPredictions = _repository.GetAllPredictions().OrderBy(y => y.DateOfPrediction);
            var allRealCases = _repository.GetAllRealCases().OrderBy(x=>x.DateOfRealCases);

            var viewStand = populateStandings(standingsDynamically, allPredictions, allRealCases);
            return View(viewStand);
        }
        List<Standings> populateStandings(List<Standings> standingsDynamically, IEnumerable<Predictions> allPredictions, IEnumerable<RealCases> allRealCases)
        {
            var SystemPoints = _repository.AllSystemPoints();
            var maxIntSystemPoint = SystemPoints.OrderByDescending(x => x.LessOrEqualThanDif).First().LessOrEqualThanDif;
            foreach (var realCase in allRealCases)
            {
                var sth = _repository.BestPredictNoByDate().Where(b => b.DateOfPrediction == realCase.DateOfRealCases).ToList();
                if (sth.Count>0) {
                    var bestPredByDate = _repository.BestPredictNoByDate().Where(b => b.DateOfPrediction == realCase.DateOfRealCases).Select(x=>x.CasesOfPrediction).ToList();
                    var PredictionsBydate = _repository.PredictionsByDate(realCase.DateOfRealCases);
                    foreach (var predictionItem in PredictionsBydate)
                    {
                            foreach (var standingItem in standingsDynamically)
                            {
                                if (predictionItem.PlayerName == standingItem.PlayerName)
                                {
                                    standingItem.PredictionsNo += 1;
                                    standingItem.DifFromRealCases += Math.Abs(predictionItem.CasesOfPrediction - realCase.RealCasesNo);
                                    if (bestPredByDate.Contains(predictionItem.CasesOfPrediction))
                                    {
                                    int diffFromRealCase = Math.Abs(predictionItem.CasesOfPrediction - realCase.RealCasesNo);
                                        standingItem.CloserPredictionsNo += 1;
                                        if (diffFromRealCase > maxIntSystemPoint) {
                                            standingItem.Points += 1;
                                            break;
                                        }
                                        else {
                                            foreach (var item in SystemPoints)
                                            {
                                                if (diffFromRealCase >= item.MoreOrEqualThanDif &&
                                                    diffFromRealCase <= item.LessOrEqualThanDif)
                                                {
                                                    standingItem.Points += item.CategoryPoints;
                                                    break;
                                                }
                                            }
                                        }                                       
                                    }
                                }
                            }
                    }
                }               
            }
            int positionCnt = 0;
            List<Standings> standings = standingsDynamically.OrderBy(m => m.PredictionsNo).OrderBy(w => w.DifFromRealCases).OrderByDescending(p => p.CloserPredictionsNo).OrderByDescending(p => p.Points).ToList();
            foreach (var item in standings)
            {
                item.PositionNo = positionCnt + 1;
                positionCnt += 1;
            }
            return standings;
        }
    }
}

CoronaPredictionsAspNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Corona Predictions Asp .Net Core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/fontawesome.css" />
    <script src="@Url.Content("~/Scripts/jquery-ui.min.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Scripts/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
    <link href="~/lib/font-awesome/css/fontawesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand navbar-left" asp-area="" asp-controller="Home" asp-action="Index">Corona Predictions Asp .Net Core</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">
                                <i class="fas fa-user"></i> Players
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RealCases" asp-action="Index"> 
                                <i class="fas fa-clinic-medical"></i> Real Cases
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Predictions" asp-action="Index">
                                <i class="fas fa-balance-scale"></i> Predictions
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PointSystems" asp-action="Index">
                                <i class="fas fa-chart-bar"></i> Point System
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Standings" asp-action="OverallStandings">
                                <i class="fas fa-trophy"></i> Overall Standings
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PlayerOfDay" asp-action="PlayersOfTheDay">
                                <i class="fas fa-star"></i> Player(s) Of the Day
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CoronaPredictionsAspNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <environment include=”Development”>
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
    </environment>
    <environment exclude=”Development”>
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    </environment>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>